name: Task
description: A specific piece of work to be completed
title: "[TASK] "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Task Template
        Use this for individual pieces of work.

  - type: input
    id: epic
    attributes:
      label: Parent Epic
      description: Which epic does this belong to?
      placeholder: "#123 or 'None'"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system?
      options:
        - core/gateway
        - core/bus
        - core/salsa
        - core/llm-proxy
        - channels/webchat
        - channels/slack
        - channels/discord
        - channels/telegram
        - tools/filesystem
        - tools/browser
        - tools/code-runner
        - cli
        - docs
        - infrastructure
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: Describe the task in detail
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this task is done?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests passing
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Technical Notes
      description: Implementation hints, relevant files, etc.
      placeholder: |
        - See `core/gateway/src/router.ts`
        - Use TypeBox for schema

  - type: dropdown
    id: size
    attributes:
      label: Size Estimate
      options:
        - XS (< 2 hours)
        - S (2-4 hours)
        - M (1 day)
        - L (2-3 days)
        - XL (1 week)
    validations:
      required: true
